### ISSUE TITLE
Selainhistoria Inbox -näkymässä

### ISSUE THREAD

**Issue by heivi** [teraton/jotu2015#22]
Kirjautuneena, kun oikeasta ylälaidasta menee Inbox -näkymään, ei selaimen edellinen -painike toimi. Mahdollisesti liittyy issue #7. Testattu selaimilla Safari ja Mozilla Firefox.

**Comment by suojakuokka** [comment]
Ei toimi myöskään Chromella

**Comment by suovo** [comment]
Ei myöskään IE:llä.

**Comment by systa** [comment]
Sama kuin 57.
